// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_user.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    nome,
    email,
    senha
) VALUES (
    $1, $2, $3
)
RETURNING id, nome, email, created_at, updated_at
`

type CreateUserParams struct {
	Nome  string
	Email string
	Senha string
}

type CreateUserRow struct {
	ID        uuid.UUID
	Nome      string
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Nome, arg.Email, arg.Senha)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
