// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_user_password.sql

package db

import (
	"context"
)

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET senha = $2, updated_at = CURRENT_TIMESTAMP
WHERE email = $1
RETURNING id, nome, email, senha, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	Email string
	Senha string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, arg.Email, arg.Senha)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Senha,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
