// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_user_email.sql

package db

import (
	"context"
)

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users
SET email = $2, update_at = CURRENT_TIMESTAMP
WHERE email = $1 
RETURNING id, nome, email, senha, created_at, updated_at
`

type UpdateUserEmailParams struct {
	Email   string
	Email_2 string
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserEmail, arg.Email, arg.Email_2)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Senha,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
