name: CI - Testes Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Rodar testes com cobertura
      run: |
        go test -v -coverprofile=coverage.out ./...
        go tool cover -func=coverage.out | tee result.log

    - name: Upload de relatório HTML
      run: go tool cover -html=coverage.out -o coverage.html

    - name: Upload artefato de cobertura
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.html
